sudo: false

language: node_js

node_js:
  - "5"
  - "6"

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm run build

after_script:
  - cd ../
  - rm -rf out
  - mkdir out
  - git clone "https://${GH_REF}" out
  - cd out
  - mkdir vue-git-repos
  - cp -r ../vue-git-repos/dist/. ./vue-git-repos
  - git config user.name "anhuisunfei"
  - git config user.email "anhuisunfei@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push "https://${GH_TOKENS}@${GH_REF}" master:master
# E: Build LifeCycle


env:
 global:
   - GH_REF: github.com/anhuisunfei/anhuisunfei.github.io.git
